// Stable public entrypoint for the building rendering stack.
// Callers should prefer this facade so the implementation can be swapped later
// without a broad import rewrite.
export * from './map-3d-utils.js';
export {
  BUILDING_FEATURE_KIND,
  BUILDING_PART_FEATURE_KIND,
  BUILDING_REMAINDER_FEATURE_KIND,
  OVERPASS_BUILDING_SOURCE_ID,
  applyBuildingPartsLayerVisibility,
  applyBuildingThemePaint,
  bindMapInteractionHandlers,
  buildRegionBuildingHighlightFilterExpression,
  buildRegionBuildingLayerFilterExpression,
  buildVisibleBuildingSelectionScopeExpression,
  ensureOverpassBuildingSourceAndLayers,
  ensureRegionBuildingSourceAndLayers,
  getBasemapBuildingLayerIds,
  getBasemapSuppressedLayerIds,
  getCurrentBuildingHoverExtrusionLayerIds,
  getCurrentBuildingHoverFillLayerIds,
  getCurrentBuildingHoverLineLayerIds,
  getCurrentBuildingPartExtrusionLayerIds,
  getCurrentBuildingPartFillLayerIds,
  getCurrentBuildingPartFilterHighlightExtrusionLayerIds,
  getCurrentBuildingPartFilterHighlightFillLayerIds,
  getCurrentBuildingPartFilterHighlightLineLayerIds,
  getCurrentBuildingPartLineLayerIds,
  getCurrentBuildingsExtrusionLayerIds,
  getCurrentBuildingsFillLayerIds,
  getCurrentBuildingsLineLayerIds,
  getCurrentBuildingSourceConfigs,
  getCurrentFilterHighlightExtrusionLayerIds,
  getCurrentFilterHighlightFillLayerIds,
  getCurrentFilterHighlightLineLayerIds,
  getCurrentOverpassBuildingHoverExtrusionLayerIds,
  getCurrentOverpassBuildingHoverFillLayerIds,
  getCurrentOverpassBuildingHoverLineLayerIds,
  getCurrentOverpassBuildingPartExtrusionLayerIds,
  getCurrentOverpassBuildingPartFillLayerIds,
  getCurrentOverpassBuildingPartFilterHighlightExtrusionLayerIds,
  getCurrentOverpassBuildingPartFilterHighlightFillLayerIds,
  getCurrentOverpassBuildingPartFilterHighlightLineLayerIds,
  getCurrentOverpassBuildingPartLineLayerIds,
  getCurrentOverpassBuildingsExtrusionLayerIds,
  getCurrentOverpassBuildingsFillLayerIds,
  getCurrentOverpassBuildingsLineLayerIds,
  getCurrentOverpassFilterHighlightExtrusionLayerIds,
  getCurrentOverpassFilterHighlightFillLayerIds,
  getCurrentOverpassFilterHighlightLineLayerIds,
  getCurrentOverpassSelectedExtrusionLayerIds,
  getCurrentOverpassSelectedFillLayerIds,
  getCurrentOverpassSelectedLineLayerIds,
  getRegionLayerIds,
  getCurrentSelectedExtrusionLayerIds,
  getCurrentSelectedFillLayerIds,
  getCurrentSelectedLineLayerIds,
  removeRegionBuildingSourceAndLayers
} from './map-layer-utils.js';
